from django.db import models
from django.utils import timezone
#from django.contrib.auth.models import User

class Video(models.Model):
    aid = models.CharField(max_length=300)
    score = models.IntegerField()
    upName = models.CharField(max_length=300)
    upID = models.CharField(max_length=300)
    guankan = models.IntegerField()
    commentNumber = models.IntegerField()
    danmu = models.IntegerField()
    like = models.IntegerField()
    shoucang = models.IntegerField()
    coin = models.IntegerField()
    share = models.IntegerField()
    nowRank = models.IntegerField()
    hisRank = models.IntegerField()
    data_posted = models.DateTimeField(default=timezone.now)

class BaiduVote(models.Model):
    name = models.CharField(max_length=300)
    vote = models.IntegerField()
    data_posted = models.DateTimeField(default=timezone.now)

class LatestVideo(models.Model):
    aid = models.CharField(max_length=300)
    score = models.IntegerField()
    title = models.CharField(max_length=300)
    tid = models.IntegerField()
    tname = models.CharField(max_length=300)
    date = models.CharField(max_length=300)
    duration = models.IntegerField()
    upName = models.CharField(max_length=300)
    upID = models.CharField(max_length=300)
    guankan = models.IntegerField()
    commentNumber = models.IntegerField()
    danmu = models.IntegerField()
    like = models.IntegerField()
    shoucang = models.IntegerField()
    coin = models.IntegerField()
    share = models.IntegerField()
    nowRank = models.IntegerField()
    hisRank = models.IntegerField()
    data_posted = models.DateTimeField(default=timezone.now)

class TotalRankVideo(models.Model):
    aid = models.CharField(max_length=300)
    score = models.IntegerField()
    title = models.CharField(max_length=300)
    tid = models.IntegerField()
    tname = models.CharField(max_length=300)
    date = models.CharField(max_length=300)
    duration = models.IntegerField()
    upName = models.CharField(max_length=300)
    upID = models.CharField(max_length=300)
    guankan = models.IntegerField()
    commentNumber = models.IntegerField()
    danmu = models.IntegerField()
    like = models.IntegerField()
    shoucang = models.IntegerField()
    coin = models.IntegerField()
    share = models.IntegerField()
    nowRank = models.IntegerField()
    hisRank = models.IntegerField()
    data_posted = models.DateTimeField(default=timezone.now)

class MostClickVideo(models.Model):
    aid = models.CharField(max_length=300)
    score = models.IntegerField()
    title = models.CharField(max_length=300)
    tid = models.IntegerField()
    tname = models.CharField(max_length=300)
    date = models.CharField(max_length=300)
    duration = models.IntegerField()
    upName = models.CharField(max_length=300)
    upID = models.CharField(max_length=300)
    guankan = models.IntegerField()
    commentNumber = models.IntegerField()
    danmu = models.IntegerField()
    like = models.IntegerField()
    shoucang = models.IntegerField()
    coin = models.IntegerField()
    share = models.IntegerField()
    nowRank = models.IntegerField()
    hisRank = models.IntegerField()
    data_posted = models.DateTimeField(default=timezone.now)

class UpInfo(models.Model):
    mid = models.IntegerField()
    name = models.CharField(max_length=300)
    fans = models.IntegerField()
    follow = models.IntegerField()
    article = models.IntegerField()
    levelInfo = models.IntegerField()
    totalVideoView = models.IntegerField()
    totalarticleView = models.IntegerField()
    score = models.IntegerField()
    data_posted = models.DateTimeField(default=timezone.now)