# Generated by Django 2.1.4 on 2018-12-06 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=300)),
                ('score', models.IntegerField(default=0)),
                ('upName', models.CharField(max_length=300)),
                ('upID', models.CharField(max_length=300)),
                ('guankan', models.IntegerField()),
                ('commentNumber', models.IntegerField()),
                ('danmu', models.IntegerField()),
                ('like', models.IntegerField()),
                ('shoucang', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('share', models.IntegerField()),
                ('nowRank', models.IntegerField()),
                ('hisRank', models.IntegerField()),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
