# Generated by Django 2.1.4 on 2018-12-11 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('vote', models.IntegerField()),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LatestVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('upName', models.CharField(max_length=300)),
                ('upID', models.CharField(max_length=300)),
                ('guankan', models.IntegerField()),
                ('commentNumber', models.IntegerField()),
                ('danmu', models.IntegerField()),
                ('like', models.IntegerField()),
                ('shoucang', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('share', models.IntegerField()),
                ('nowRank', models.IntegerField()),
                ('hisRank', models.IntegerField()),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MostClickVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('upName', models.CharField(max_length=300)),
                ('upID', models.CharField(max_length=300)),
                ('guankan', models.IntegerField()),
                ('commentNumber', models.IntegerField()),
                ('danmu', models.IntegerField()),
                ('like', models.IntegerField()),
                ('shoucang', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('share', models.IntegerField()),
                ('nowRank', models.IntegerField()),
                ('hisRank', models.IntegerField()),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TotalRankVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=300)),
                ('tid', models.IntegerField()),
                ('tname', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=300)),
                ('duration', models.IntegerField()),
                ('upName', models.CharField(max_length=300)),
                ('upID', models.CharField(max_length=300)),
                ('guankan', models.IntegerField()),
                ('commentNumber', models.IntegerField()),
                ('danmu', models.IntegerField()),
                ('like', models.IntegerField()),
                ('shoucang', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('share', models.IntegerField()),
                ('nowRank', models.IntegerField()),
                ('hisRank', models.IntegerField()),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('fans', models.IntegerField()),
                ('follow', models.IntegerField()),
                ('article', models.IntegerField()),
                ('levelInfo', models.IntegerField()),
                ('totalVideoView', models.IntegerField()),
                ('totalarticleView', models.IntegerField()),
                ('score', models.IntegerField()),
                ('data_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='score',
            field=models.IntegerField(),
        ),
    ]
